[Unit]
Description=Gunicorn daemon for Django Reconhecimento Facial
After=network.target

[Service]
User=ubuntu
Group=www-data
WorkingDirectory=/home/ubuntu/APS6-2.0/reconhecimentofacial
Environment="PATH=/home/ubuntu/APS6-2.0/.venv/bin"
Environment="DJANGO_SETTINGS_MODULE=reconhecimentofacial.settings"

ExecStart=/home/ubuntu/APS6-2.0/.venv/bin/gunicorn \
    --workers 3 \
    --timeout 300 \
    --bind unix:/home/ubuntu/APS6-2.0/reconhecimentofacial/gunicorn.sock \
    --access-logfile /home/ubuntu/APS6-2.0/logs/gunicorn-access.log \
    --error-logfile /home/ubuntu/APS6-2.0/logs/gunicorn-error.log \
    reconhecimentofacial.wsgi:application

Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
